### ISSUE TITLE
Items that are currently not working

### ISSUE THREAD

**Issue by getsetbro** [pattern-lab/patternlab-node#106]
Comment thread is empty
http://getsetbro.com/pl-nodeV8/public/?p=organisms-comment-thread

Carousel
http://getsetbro.com/pl-nodeV8/public/?p=organisms-carousel

Accordion
http://getsetbro.com/pl-nodeV8/public/?p=molecules-accordion
But I see it doesn't do anything on the PHP demo
http://demo.patternlab.io/?p=molecules-accordion

**Comment by bmuenzenmeyer** [comment]
Hi Seth - thanks for the ping on twitter. I saw this the other day. I plan to look at another round of fixes soon.

**Comment by bmuenzenmeyer** [comment]
Curious @dmolsen if you think we should even ship with working UI components like a carousel. Pattern Lab is not a UI framework, and I worry about people attempting to use a OOB accordion or carousel. Like most things, we should strike a balance between example uses and vanilla tool/platform.

**Comment by dmolsen** [comment]
@bmuenzenmeyer -

My answer is "no." The demo was a bit of mistake. As @bradfrost notes in `styles.css` "...please don't use these styles. They're just here to put together the demo, and nothing more." PL2 has an empty base StarterKit ([Twig example](https://github.com/pattern-lab/starterkit-twig-base)). The demo will still be available as a StarterKit but hopefully the directions guide them towards building their own thing first from the "empty" one. If maintaining the back-end of PL is time consuming I couldn't imagine maintaining real, tested UI patterns.

**Comment by getsetbro** [comment]
If I were to make a starter kit seeded with bootstrap components, where should that live?

**Comment by getsetbro** [comment]
I'm considering making a bootstrap based starter kit. Thoughts?

**Comment by dmolsen** [comment]
@getsetbro -

I think it would be awesome. I have a defined file structure format for StarterKits installs in PL2 for PHP. If that could be used that would be great. It should work just fine for Node too since the worse thing that happens is someone downloads the StarterKit and copies and pastes a directory.

[Example structure](https://github.com/pattern-lab/starterkit-mustache-demo)
[Example `composer.json` for simplifying installs w/ PL2 for PHP](https://github.com/pattern-lab/starterkit-mustache-demo/blob/0fcc339a0b4b2f18fdb43fca713c4057b130b8b5/composer.json)

It can live under your account. Frankly, that'd be best.

**Comment by getsetbro** [comment]
I was expecting it to be the source folder but I see you have the dist?

If I use just html and nothing mustache or twig specific than it will be agnostic. But what would the file extension be? "file.html"?

**Comment by bmuenzenmeyer** [comment]
In the case of pl node, you could save pure HTML as .mustache and it would
get picked up fine IIRC.

**Comment by getsetbro** [comment]
FYI, this might be another bug. A css file added to source/css/ does not get copied to public/css but a JS file added to source/js/ does get copied to public/js.

**Comment by bmuenzenmeyer** [comment]
Not a "bug," just a oversight in `Gruntfile.js`:

     { expand: true, cwd: './source/js/', src: '*', dest: './public/js/'},
     { expand: true, cwd: './source/css/', src: 'style.css', dest: './public/css/' },

Change the css src to `'*'`

Will change in my working copy of dev.

**Comment by bmuenzenmeyer** [comment]
@getsetbro to answer your comment more directly about the bootstrap version - I echo how cool this would be but agree with Dave in that it should be a starter-kit repo not part of pl-node core. PatternLab is not a ui framework. Shipping with Bootstrap is far too opinionated.

That said, if you build this, I would be more than happy to add it to our readme or start a wiki. I've been kicking around the idea of a wiki for a while since patternlab.io/docs are in flux.

**Comment by bmuenzenmeyer** [comment]
Per this conversation and https://github.com/pattern-lab/patternlab-node/issues/109 I am closing this issue
