### ISSUE TITLE
Resolve broken links in new docs site

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#1153]
I used https://validator.w3.org/checklink to checkout our new doc site, previewed at: https://patternlab-docs-preview.netlify.app/

This is prerequisite for cutting over the docs site.

There are a number of broken links we need to resolve. My best attempt at scraping the w3c results and deduping looks like this:

https://patternlab-docs-preview.netlify.app/resources
https://patternlab.io//docs/template-language-and-patternengines/
https://patternlab-docs-preview.netlify.app/resources/
https://patternlab.io//docs/starterkits/
https://patternlab-docs-preview.netlify.app/docs/pattern-reorganizing.html
https://patternlab-docs-preview.netlify.app/docs
https://patternlab.io//feed.xml
https://patternlab.io//docs/using-pattern-states/
https://patternlab.io//updates/
https://patternlab.io//docs/managing-pattern-assets/
https://patternlab.io//docs/creating-pattern-specific-values/
https://patternlab.io//docs/modifying-the-pattern-header-and-footer/
https://patternlab-docs-preview.netlify.app/docs/advanced-auto-regenerate.html
https://patternlab-docs-preview.netlify.app/docs/pattern-including.html
https://patternlab.io//docs/keyboard-shortcuts/
https://patternlab.io//docs/using-pseudo-patterns/

cc @frostyweather @bradfrost

**Comment by frostyweather** [comment]
@bmuenzenmeyer A few comments and questions:
- https://patternlab-docs-preview.netlify.app/docs/pattern-reorganizing.html has changed to https://patternlab-docs-preview.netlify.app/docs/reorganizing-patterns/ in the new site.

Do these need to have the same URL structure as the live site or is it okay for these to be different? I think most of the URLs posted above from the new site are just because the title has been renamed.

**Comment by bmuenzenmeyer** [comment]
Good questions.  The crawler found those links somewhere on the new site and they broke.  Navigate around and you will find some. 

The goal is to ferret these out wherever they are

**Comment by frostyweather** [comment]
@bmuenzenmeyer Alrighty. I found the issue with resources. I'll take a look at the others and fix them if they need to be fixed.

**Comment by frostyweather** [comment]
@bmuenzenmeyer @bradfrost For the documentation page, do we still want that since all of our docs are in the nav now?

**Comment by frostyweather** [comment]
@bmuenzenmeyer @bradfrost In terms of the new site:

- https://patternlab-docs-preview.netlify.app/docs/pattern-reorganizing.html has changed to https://patternlab-docs-preview.netlify.app/docs/reorganizing-patterns/
- https://patternlab-docs-preview.netlify.app/docs. Should this exist since it exists in the nav?
- https://patternlab-docs-preview.netlify.app/docs/advanced-auto-regenerate.html is not in the new site (or if it is, I don't know where it is mapped to).
- https://patternlab-docs-preview.netlify.app/docs/pattern-including.html has been changed to https://patternlab-docs-preview.netlify.app/docs/including-patterns/

Assuming those are the ones we should focus on since we are launching the new site soon.

**Comment by frostyweather** [comment]
@bmuenzenmeyer Just created a pull request for this. All of the new links should be resolved. The old links from above have either been renamed or no longer have any significance.
