### ISSUE TITLE
Request for input: make pattern engine loading explicit via the PL config

### ISSUE THREAD

**Issue by ringods** [pattern-lab/patternlab-node#1251]
This issue is to discuss the changes in loading pattern engines. It requires input from the core team: @bmuenzenmeyer @bradfrost @sghoweri @JosefBredereck and whoever I am forgetting.

In #1225 & #1246, I changed the way how resources from UIKits are loaded: via the NodeJS resolver (`require.resolve`). For this to work, it now requires the property `package`, with a fallback at the moment based on `name` but which will be removed in the future. This makes it the loading explicit: first add the UIKit as a package dependency, then resolve the resources and copy them. Using the resolver also makes this feature working independent of the package manager.

The next piece of code loading that needs to go via the resolver is the loading of pattern engines. The current code is again scanning the `node_modules` folder in 2 different locations manually:

https://github.com/pattern-lab/patternlab-node/blob/931b390af8abb7c9e6428d4fa27262d0af8b9dd2/packages/core/src/lib/pattern_engines.js#L12-L21

It returns every package which matches `engine-` in the package name:

https://github.com/pattern-lab/patternlab-node/blob/931b390af8abb7c9e6428d4fa27262d0af8b9dd2/packages/core/src/lib/pattern_engines.js#L23-L37

Like UIKits, this is not explicit and can lead to incorrect packages being found. If we want to make it explicit, the PatternLab configuration needs to be extended with an explicit mention of the pattern engines which must be loaded. But how should this look?

* Should the config only specify a single pattern engine or should it be a list?
* For each of the pattern engines, is more config needed besides the package name?

Any further suggestions?

**Comment by JosefBredereck** [comment]
I'm completely on your side on this topic. I would recommend defining by a package which engine should be loaded for engines, kits, plugins, and other stuff that we ever plan in the future. Only relying on the name could lead to unintentional errors, because of deep dependencies in other public packages.

Adding also my question from this ticket: https://github.com/pattern-lab/patternlab-node/issues/872#issuecomment-466959518 because it also references to the pluing loading by name and not package.

**Comment by bmuenzenmeyer** [comment]
I agree, everything should be explicit from the config!
