### ISSUE TITLE
Change title of patterns / components

### ISSUE THREAD

**Issue by SaroGFX** [pattern-lab/patternlab-node#1336]
The titles of the patterns are automatically pulled from the file name and the directory name. You can change the individual components through a title declaration in the .md files. But this does not work for the directory name.

Is it possible to change the way how patternlab displays directory names? E.g. _message-box would be `Message Box` instead of `_Message-box`.

Thanks

**Comment by JosefBredereck** [comment]
Hello @SaroGFX, if you need that function for ordering your directories, please have a look at [Re-ordering pattern groups and subgroups](https://patternlab.io/docs/reorganizing-patterns/#heading-re-ordering-pattern-groups-and-subgroups)

Currently, it is not possible to change the Title of groups directly

**Comment by mfranzke** [comment]
@SaroGFX What I'm wondering about: If you create a pattern like e.g. `/source/_patterns/organisms/message-box/message-box.hbs`, its title would even already get displayed as you mentioned: `Message Box`
![image](https://user-images.githubusercontent.com/787658/122795562-be66eb80-d2bd-11eb-9479-1d7cc32025a8.png)

Or do you mean the displayed title at some other place where we haven't thought about so far?

I've recognized that you additionally had an underscore at the beginning of your example – this older way of prepending patterns or groups by that underscore to hide them is deprecated and should get replaced by hiding them from the responding `.md` files (which most likely wasn't your expected result anyhow).

**Comment by coreylafferty** [comment]
If I'm understanding what @SaroGFX is asking for, I think it'd be a great addition.  Especially once numbered ordering for subgroups/folders (currently deprecated) is completely removed.

Assuming his folder structure is something like this:
```
organisms/message-box/message-box.twig
organisms/message-box/message-box.md
organisms/message-box/_message-box.md
```

I think the underscore before the MD file in his example is to apply to the Subgroup (folder) Message Box, as opposed to the message-box.twig file inside it, which is how you create MD files for subgroups/folders since the underscore has been deprecated as a hiding mechanism.  

So, to alter the title, hidden status or order of message-box.twig (within the message-box folder), you'd create a file called `message-box.md` and put this inside it.

```
---
title: 'My New Title'
order: -1
hidden: true
```
And that would change the display of what's WITHIN the message-box subgroup/folder.

Similarly, if you wanted to change the hidden status or order of the SUBGROUP/FOLDER, you'd create a file called `_message-box.md` and put pretty much the same thing inside it.

```
---
order: -1
hidden: true
```

However, only those two properties currently work for subgroups/folders.  Title does not currently do anything, even if you add it.

I'd love to see the 'title' property in the MD files working for folders (I did try to create a PR to accomplish that a while back, but got lost in the logic for subgroup title creation).  It will be especially important once the numbered ordering is removed for folders (e.g., 01-components).  In our current starter kit, we use those numbers both for ordering within pattern lab AND so the folders appear in a logical order in your IDE, instead of alphabetical.  At least in our case, it would be ideal to leave those numbers there even after numbered ordering is removed from the Pattern Lab compilation process and then just change the titled displayed for those folders within Pattern Lab using the `title` property.

**Comment by SaroGFX** [comment]
> @SaroGFX What I'm wondering about: If you create a pattern like e.g. `/source/_patterns/organisms/message-box/message-box.hbs`, its title would even already get displayed as you mentioned: `Message Box`
> ![image](https://user-images.githubusercontent.com/787658/122795562-be66eb80-d2bd-11eb-9479-1d7cc32025a8.png)
> 
> Or do you mean the displayed title at some other place where we haven't thought about so far?
> 
> I've recognized that you additionally had an underscore at the beginning of your example – this older way of prepending patterns or groups by that underscore to hide them is deprecated and should get replaced by hiding them from the responding `.md` files (which most likely wasn't your expected result anyhow).


@mfranzke It doesn't seem to behave that way in my Patternlab. I have the following folder structure: 

![Screenshot 2021-06-22 at 09 21 24](https://user-images.githubusercontent.com/3781800/122881234-38898580-d33b-11eb-8633-c05bb6751280.png)

Which displays like this

![Screenshot 2021-06-22 at 09 21 51](https://user-images.githubusercontent.com/3781800/122881321-548d2700-d33b-11eb-9f91-b5d7ffb12487.png)

**Comment by mfranzke** [comment]
@SaroGFX, okay, thanks for your feedback. I recognized that you're using the twig edition, whereas I've tested on the node edition, maybe that's the difference in our setups.

**Comment by mfranzke** [comment]
@SaroGFX I've tried to reproduce the topic on the following setup, installing a clean version via `npm create pattern-lab`:

- Pattern Lab Twig templating language
- Twig (PHP) demo patterns installed
- Mac
- node v15.14.0

(most likely the three last ones don't necessarily matter)

When setting up a new pattern like this (`/source/_patterns/molecules/message-boxes/message-box.md`; in this case as a duplication of the existing [`media`](https://github.com/pattern-lab/patternlab-node/tree/843bb33c23b1da9b43dc78b8afae8d2ecd34bfdd/packages/starterkit-twig-demo/dist/_patterns/molecules/media) pattern with the same contents as those files, but this most likely doesn't matter as well):
![image](https://user-images.githubusercontent.com/787658/123142790-19cde080-d45a-11eb-905e-319dd94d3242.png)

It gets displayed like this in the browser:
![image](https://user-images.githubusercontent.com/787658/123142904-4124ad80-d45a-11eb-9360-5a9f4c22ba17.png)

So could you please provide some more information on your setup for us to be able to reproduce that issue? And/or is your code available in a public repository?

**Comment by SaroGFX** [comment]
@mfranzke Thanks for looking into it. The repository that we're running PatternLab in is pretty big with a lot of things such as containers that I'm not super familiar with on how they work and what they do exactly, so I'm not sure what's relevant to share. But I also did a local clean install with the same settings and OS and when I changed the `molecules` folder to `components_molecules` and then `npm run start` I get this error and the styling is broken in PatternLab : 

![Screenshot 2021-07-28 at 17 17 22](https://user-images.githubusercontent.com/3781800/127349352-612e5c02-e887-4311-b58c-a73b539e3210.png)

**Comment by mfranzke** [comment]
@SaroGFX that folder might still be cached within the `dependencyGraph.json` file within the root of the patternlab installation, so after doing a „bigger“ change especially to the patterns structure like e.g. a folder renaming it might be beneficial to stop patternlab, remove that cache file and start patternlab again.
By doing the steps you've provided I could've reproduced the problem you've mentioned and added the screenshot for.

I've opened a MR to add some information on those errors: https://github.com/pattern-lab/patternlab-node/pull/1350 (and even also adding this to #1344)

**Comment by SaroGFX** [comment]
@mfranzke The issue appears to be fixed with a recent update 💪
