### ISSUE TITLE
Support Pattern Types with hyphens

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#214]
Talk to dave about whether or not hyphens should be supported. http://patternlab.io/docs/pattern-organization.html does not specify patternTypes

In general, look into the data gathering and rulesets of https://github.com/pattern-lab/patternlab-php-core/tree/dev/src/PatternLab/PatternData/Rules

**Comment by bmuenzenmeyer** [comment]
hey @dmolsen - rubber ducky time

https://github.com/pattern-lab/patternlab-php-core/blob/master/src/PatternLab/PatternData/Rules/PatternTypeRule.php#L41 would be an indication that PL PHP supports dashes in patternTypes, yes?

**Comment by dmolsen** [comment]
This would be a great time to have tests for the PHP version ;) Yes, it says that pattern types can be made up of multiple words. e.g. the pattern types "client atoms" and "internal atoms" if someone wanted to organize things that way. Haven't tested that in a long time though.

And those docs are a tad specific on what the pattern types need to be. I should update them to be a little more lenient.

**Comment by tommcc** [comment]
There are some bugs when naming top-level types with hyphens. I don't see why the naming rules for the top-level types should be any different from lower levels, and the docs don't make this clear.

I fiddled a little bit to try to fix this, but since it's going to involve changes in several places I wanted to document it here in case it's easier for someone else more familiar to fix it.

Directory/file structure:

- 00-global-styles
  - buttons.mustache

Expected menu structure:

- Global Styles
  - Buttons

Actual menu structure:

- Global
  - Global Styles
    - Buttons
  - View All
