### ISSUE TITLE
Fuzzy partial matching should prefer exact match

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/patternlab-node#226]
So I have two molecules with these filenames:

- 00-primary-nav.mustache
- 00-primary-nav-jagged.mustache

And when I have this in another file:

    {{> molecules-primary-nav }}

It includes the "jagged" variation; it should include the first one as it's an exact match.

**Comment by bmuenzenmeyer** [comment]
Hi Evan. 
So I'm clear, are you proposing something like moving this block to be evaluated first?

https://github.com/pattern-lab/patternlab-node/blob/dev/builder/pattern_assembler.js#L258-L261

**Comment by EvanLovely** [comment]
Yep! If it's exact then that it feels very specific and intentional to me; if no exact match: then let's fuzzy find it. Probably would be slightly faster too.

I found it happening to me again with these two partials:

- byline.mustache
- block-headline-byline.mustache

When trying to `{{> molecules-byline }}`

**Comment by bmuenzenmeyer** [comment]
And you're running against a `dev` version of PL Node or 1.0.0 ?

**Comment by EvanLovely** [comment]
Yep, on d01383a specifically

**Comment by bmuenzenmeyer** [comment]
@EvanLovely can you review https://github.com/pattern-lab/patternlab-node/commit/0173a0ad760530c4bae4f47f26740b3231fc80fcand make sure it's to your liking? because I store all patterns in an array instead of an object, I think I must loop through instead of directly addressing, up to 3 times in the case of fuzzy matches. In most cases people will hit the first loop, using the preferred syntax.

**Comment by bmuenzenmeyer** [comment]
Assuming this looks good - this issue will automatically closes when it hits master

**Comment by EvanLovely** [comment]
Looks good; thanks for getting this!
