### ISSUE TITLE
Refactor Pattern Object

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#246]
- [x] rename `oPattern` to `Pattern`
- [x] simplify constructor to remove redundant and derivative parameters
- [x] anything else worth looking into

**Comment by geoffp** [comment]
I am so into this.

**Comment by geoffp** [comment]
@bmuenzenmeyer, I was thinking it makes the most sense to do this on the `pattern-engines` branch because that object has already seen lots of extension there. Is that all right with you?

**Comment by bmuenzenmeyer** [comment]
you bet

**Comment by geoffp** [comment]
This is now in progress at [this branch](https://github.com/pattern-lab/patternlab-node/tree/refactor-oPattern). I'm exploring the idea of making pattern paths relative to the pattern directory -- I think the logic is simpler that way and less information is needed.

**Comment by bmuenzenmeyer** [comment]
Hey Geoff,

Can you elaborate on why it's better? with liberal use of `path.resolve()` I don't think it matters one way or another as far as I know.

**Comment by geoffp** [comment]
Well, I'm not 100% sold on it myself, but I felt like I had to go down that road to see where it leads. Maybe I was over-focused on the goal of a simple `Pattern` constructor that doesn't need many arguments, but here's how it went.

I realized that if we don't pass the `subdir` to the pattern constructor explicitly, we need to calculate it; that was the plan all along. The monkeywrench came when I realized that the subdir could be either a single directory (as you know, patterns can show up directly in top-level categories) or two, giving me no way to know if the subdir should be the last one or two directories in the path. However -- if the path is always relative to the pattern tree root, it's trivial to get the `subdir` -- it's always the directory portion of the path. No more, no less.

This *may* muddy the waters if someday we have patterns being composed from multiple libraries, since patterns in that case should know which library they come from, especially if their subdir + filename match, but in that case it's maybe even more useful to add a separate libraryPath property/param than a bunch of absolute URLs we have to untangle.

**Comment by bmuenzenmeyer** [comment]
Ok. Let's see where this leads. It's a good thing we have unit tests giving us some confidence. `subdir` is all over the codebase. especially in ui_builder

**Comment by geoffp** [comment]
I think we can close this one! We've done it.

**Comment by bmuenzenmeyer** [comment]
Thanks for the poke. I typically try not to close issues until they hit `master` for some reason. Works best when they are referenced by a commit, because then Github automatically closes them, but the tag will be enough of a reminder, since this issue looks unreferenced throughout development.
