### ISSUE TITLE
Patternlab Documentation

### ISSUE THREAD

**Issue by herrjosua** [pattern-lab/patternlab-node#395]
Just some general feedback. I was trying to get the `edition-node-gulp` version of Pattern lab running locally. My issue was that my global version of Gulp was an older version, and I installed a newer version locally. But I did not realize that running `gulp ...` was using the global version and not the local version. I posted on the Gitter channel and was able to figure out the issue.

I would like to suggest editing the getting started section to include information on how to run pattern lab using a globally install version of gulp and a locally installed version of gulp. This will help users who are still learning the whole node,npm,gulp ecosystem.

**Comment by bmuenzenmeyer** [comment]
My understanding is that having a global install of gulp allows users to type `gulp commandFoo` and have it work, since it's added to a user's PATH. This command interface sees simple, albeit with a bit of upfront install cost.

To run locally instead, how would a user run the packaged tasks in the edition gulpfile? I'm asking sincerely, since I am very much on my own learning journey too.

**Comment by e2tha-e** [comment]
@herrjosua @bmuenzenmeyer 
`./node_modules/.bin/gulp patternlab:foo`

**Comment by bmuenzenmeyer** [comment]
oh - of course. is that preferred by people?

**Comment by e2tha-e** [comment]
I keep gulp 3 installed globally because all my other projects have not moved over to 4. I imagine most devs know how to alias this sort of thing for a shorter command. But beyond that, there's not much anyone can do about forward progress involving breaking changes.

**Comment by bmuenzenmeyer** [comment]
I've created https://github.com/pattern-lab/patternlab-node/wiki/Running-with-Local-Gulp-Instead-of-Global-Gulp to help address this - will be linking it into documentation shortly.
