### ISSUE TITLE
clean output html in patterns infos

### ISSUE THREAD

**Issue by gael-boyenval** [pattern-lab/patternlab-node#448]
I am using Pattern Lab Node v2.4.3 on Mac, with Node v6, using the Gulp Edition.

##### Expected Behavior

Our workflow: 
1) front-end dev are building dom éléments and patterns using PL node and mustache. 
2) Back-end guys then go there and pickup the dom in the pattern lab infos panels.

it would be great to get : 

* a cleaned html output in pattern infos panels (indent, spaces, lines, tab etc)
* <s>a copy to clipboard button to any panel displaying code</s> (into pattern-lab/styleguidekit-assets-default#20)

maybe with : ``require('js-beautify').html;``

a test here : https://github.com/pattern-lab/patternlab-node/pull/449

##### Actual Behavior

none of that

**Comment by bmuenzenmeyer** [comment]
@gael-boyenval merged and tweaked a bit. overall a good addition!

**Comment by gael-boyenval** [comment]
@bmuenzenmeyer, yes great ! :)
We should maybe add an option to the config file for the indent size. 
Every company has his own conventions
What do you think ?

**Comment by bmuenzenmeyer** [comment]
I'm opposed to adding minutiae config options like this. I understand that my change might not be what all teams are used to, but their IDE should offer formatting options and ultimately the PL code pane is about readability, which to me, is less scrolling.

That's why I said [here](https://github.com/pattern-lab/patternlab-node/pull/449#pullrequestreview-1211876) that I was hoping we could pass through any found .editorconfig to your PR's code and then truly have people define it that way. To me that's the best long-term solution and for now I'd rather not add an indent property to the configuration.
