### ISSUE TITLE
getting started w/ patternlab-node is not documented/published

### ISSUE THREAD

**Issue by cdaringe** [pattern-lab/patternlab-node#535]
##### Expected Behavior

i see patternlab as powerful when used as dependency.  i want rolling updates, which you cannot get when using a forked/cloned version of a project.  therefore, the `grunt`/`gulp` editions don't provide me much value, because the second i fork and modify, i immediately shut myself from upstream improvements in the project (as conflicts are sure to ensue).

is there a plan to make patternlab-node more established as a CLI/executable that I can "run against my project"?

##### Actual Behavior

i have to fork or copy stale-prone code to get running!

**Comment by bmuenzenmeyer** [comment]
hi @cdaringe 

> getting started w/ patternlab-node is not documented/published

[The first thing in the README](https://github.com/pattern-lab/patternlab-node#pattern-lab-node-core) is how to consume the core library using our current strategy, [editions](http://patternlab.io/docs/advanced-ecosystem-overview.html)

> i see patternlab as powerful when used as dependency. i want rolling updates, which you cannot get when using a forked/cloned version of a project.

For the most part, you are fine by using an `edition` as a subfolder in a project - because the grunt or gulp tasks they ship with are relatively stable - with almost all of the change coming from `patternlab-node` which is included as a dependency, or one of the other shared pieces of code like the frontend `styleguidekit-assets-default`

> therefore, the grunt/gulp editions don't provide me much value, because the second i fork and modify, i immediately shut myself from upstream improvements in the project (as conflicts are sure to ensue).

again, true, but has not happened with a frequency I would consider a deal-breaker. to each his own. when changes occur in those repo's i try to document them in release notes, default new config values, and warns users of missing config entries

> is there a plan to make patternlab-node more established as a CLI/executable that I can "run against my project"?

yes! as evidenced:
* in the project: https://github.com/pattern-lab/patternlab-node/projects/1
* on the original issue: https://github.com/pattern-lab/patternlab-node/issues/425
* on the open epic issue: https://github.com/pattern-lab/patternlab-node/issues/459
* on the open milestone: https://github.com/pattern-lab/patternlab-node/milestone/20
* explicitly most recent releases: https://github.com/pattern-lab/patternlab-node/releases
* inside working code! https://github.com/pattern-lab/patternlab-node-cli/tree/dev

sorry for the shade - but issues like this are a bit demoralizing to get when i feel there are adequate ways to find this information

**Comment by cdaringe** [comment]
> The first thing in the README is how to consume the core library

respectfully, how to use the editions is not what i'm after.  knowing how to use _this library_, how to use _this project_ is that which i have asked about in the title.  sorry for the lack of clarity.  i didn't want to use gulp/grunt.  i was looking into how to adapt patternlab-node into another tool, and expected some dev docs on this page. i expected to see patternlab-node's API docs.  there is a CLI page, but it's tagged WIP and, further, not for _this_ project.

so, kindly, "how to consume the core library" I still don't see documented.

> again, true, but ... of missing config entries

i (a friendly stranger) would encourage re-visiting this perspective.  you've developed what appears to be some _really cool, powerful stuff_.  the presented workflow is foreign and awkward to me.  the project offers up a tool, but never gave me a tool directly.  rather, it gave a template and instructions.  i respect the hard work you've done, but I don't want _your project_, i want my project, and your great tools.  `patternify -c my-config.json my-project/`, and kaboom!  looks like per your issues below you're already moving in this direction. 💯 can't wait to see how that turns out.

> yes! as evidenced:

thanks for the x-refs.  that's great news!  very excited about some of this, and look forward to landing some commits.  please keep in mind that you guys have _a ton_ of documentation.  rest assured that i looked.  rather than providing developer docs (the docs I expected in source control project), however, there's lot of content, like, what gulp is or information about npm.  IMHO those should remain on the user pages, not the dev pages.

whilst you're upset that I asked some repeat questions, I was disgruntled with my lack of ability to do things that I felt should be entirely obvious, but couldn't because the right docs aren't in the right place.

so (genuinely) **sorry for the shade**, i'm grateful for your response, but this issue shouldn't be demoralizing, IMHO, it should be expected.
