### ISSUE TITLE
Multiple pattern parameters down a render tree cause issues

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#539]
As reported at https://gist.github.com/teehemkay/2b88a18488fe60d3a260ccad20e79e35

**Comment by tommcc** [comment]
I posted another two reproductions of this bug on #250 but posting it here since it more correctly describes the behavior.

In the following scenarios, includes disappear when trying to view the organism's rendered output.

### Scenario 1 - Atom disappears entirely

**01-atoms/atom.mustache:**

```
I should appear!

```

**02-molecules/molecule.mustache:**

```
{{> atoms-atom(b: true) }}

```

**03-organisms/organism.mustache:**

```
{{> molecules-molecule(a: true) }}
```

### Scenario 2 - Atom disappears entirely

**01-atoms/atom.mustache:**

```
I should appear!

```

**02-molecules/molecule.mustache:**

```
{{> atoms-atom:x }}

```

**03-organisms/organism.mustache:**

```
{{> molecules-molecule(a: true) }}
```

**Comment by bmuenzenmeyer** [comment]
I've updated https://github.com/pattern-lab/starterkit-mustache-acidtest/issues/1 with the results of my spec-parity testing between PL PHP and PL Node. 

Now, to fix!
