### ISSUE TITLE
View All Broken

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#835]
I am using Pattern Lab Node `v3.0.0-alpha.11` on `Windows`, with Node `v8.9.4`, using a `Gulp` Edition.

##### Actual Behavior

![image](https://user-images.githubusercontent.com/298435/38142671-de2c6e98-3402-11e8-9fa0-0a0112212de1.png)

##### Steps to Reproduce

Click on the Pattern Type Title
"View All" menu options similarly do not work

**Comment by julrich** [comment]
It seems the link is broken already when the footer is inserted here:
https://github.com/pattern-lab/patternlab-node/blob/master/packages/core/src/lib/buildFooter.js#L35

It inserts `{"patternPartial":"viewall-atoms-0"}` for me, for example. Where it should insert `viewall-atoms-buttons`, for example.

Still not sure where it goes wrong exactly.

Used a conditional on the breakpoint to catch it (used `footerPartial.indexOf('-0') > -1;` for that).

**Comment by bmuenzenmeyer** [comment]
thanks for the additional info!

**Comment by julrich** [comment]
Not proposing this as the actual fix, because it feels like this should be solvable much cleaner, but this fixed the problem for me, for now:
https://github.com/ruhmesmeile/patternlab-node/pull/2/files

Basically `patternSubtype` seems to be just an index, not the name of the pattern. I could retrieve it like this, which seems to fix the structure of the link in the generated footer / view all pattern:
```
{"patternPartial":"viewall-atoms-button"}
```
instead of:
```
{"patternPartial":"viewall-atoms-0"}
```

**Comment by bmuenzenmeyer** [comment]
> Basically patternSubtype seems to be just an index, not the name of the pattern

This certainly sounds like the case. I am curious if it was a regression on my part as part of the pretty massive async refactor. Cleaning up all the ui_builder code with this issue in mind will help. I'll dig into this soon! My first step will be trying to isolate this behavior to the point where we can write a failing unit test.

**Comment by julrich** [comment]
Added some more fixes to the PR above, with those changes, at least it's behaving consistently.

I think the `let p;` need to be scoped like this, because otherwise this line:
https://github.com/pattern-lab/patternlab-node/blob/master/packages/core/src/lib/ui_builder.js#L595

The same path is re-used for different patterns, resulting in only one of them getting it's `viewall-` index.html file.
