### ISSUE TITLE
[core] Remove plugin installation code

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#872]
As part of https://github.com/pattern-lab/patternlab-node/issues/812 I expect to be able to run all plugin installation / enabling / disabling logic through the CLI.

For example:

```
npm run patternlab install --plugins @pattern-lab/plugin-tab
```

This code when operating successfully does not need core at all.

`core/src/lib/plugin_manager.js`

- [ ] installPlugin
- [ ] enablePlugin
- [ ] disablePlugin

`core/src/index.js`

- [ ] installplugin

`edition-node-gulp/gulpfile.js`

- [ ] patternlab:installplugin

- [ ] regen docs

**Comment by bmuenzenmeyer** [comment]
blocked by https://github.com/pattern-lab/patternlab-node/issues/873

**Comment by bmuenzenmeyer** [comment]
Hoping  this can be removed once https://github.com/pattern-lab/patternlab-node/issues/812 is resolved

**Comment by SlimeGames** [comment]
I have a specific question on this topic. If I understood the plugin loading feature correctly. 

In patternlab.js we initialize all plugins. 
```JS
initializePlugins(patternlab) {
    if (!patternlab.config.plugins) {
      return;
    }
    plugin_manager.intialize_plugins(patternlab);
  }
```
But what is happening? While we initialize our plugins we try to find all possible plugins in the node_modules directory. The user has to configure all plugins under patternlab.config.plugins but why are we searching for all possible plugins instead of using the given?

As far as I know, the plugin `@pattern-lab/plugin-tab` is configured as `pattern-lab-plugin-tab` and it looks like we are searching the node_modules folder for all files and after that process, we try to match with the patternlab.config file.

An alternate way would be to use the "plugin name" as a loader because the user has to configure if he wants to enable this plugin or not. There are two ways for doing this.

```JSON
"plugins": {
    "@pattern-lab/plugin-tab": {
      "enabled": true,
      "initialized": false,
      "options": {
        "tabsToAdd": []
      }
    }
  }
```
**OR**
```JSON
"plugins": {
    "pattern-lab-plugin-tab": {
      "enabled": true,
      "node": "@pattern-lab/plugin-tab",
      "initialized": false,
      "options": {
        "tabsToAdd": []
      }
    }
  }
```
The benefits will be, that we don't have to read the whole dictionary again and that we are 100 percent sure to take the right plugin. Also, the `initialized` parameter can be added later to the patternlab.config since it is only relevant for the initialization status while running patternlab.
