### ISSUE TITLE
Add documentation how to user other PatternEngines

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#952]
This should probably exist on the docs site, but opening here.

**Comment by engelfrost** [comment]
This sounded like a good thing to add but I've run into some questions: 

1. How much should the documenation encourage picking a pattern engine? Should the documentation encourage moving away from the hacked Mustache templates? 
2. The behaviour of the `patternExtension` config property is unexpected to me. What is it supposed to do? (I expected it to control which pattern extension to identify as templates, but it seems that both `.hbs` and `.mustache` templates are processed regardless of this setting. Of course, mixing Handlebars and Mustache does not work very well... Setting the property to anything other than `"mustache"` or `"hbs"` causes errors, but it does not seem to matter which of those two values I set the option to).

**Comment by engelfrost** [comment]
Thanks!

1: Good point. For another issue, would it be a good idea to put all Mustache-specific documentation separately, since it's important in PL3 to distinguish between what PL does and what PL flavored Mustache does? 

2: IMO the config should specify the pattern engine (not the file extension), and the pattern engine should tell PL what file extensions to use. If the extension needs to be configurable this belongs under a pattern engine config. But changing this is probably a little late for v3? 

Anyway, your explanation makes sense. I'm getting some confusing results since "pure" Mustache is (almost?) compatible with Handlebars. I'll do some testing with Nunjucks instead to make sure patterns fail if the wrong engine is used, that should make things easier for me.

**Comment by engelfrost** [comment]
Seems I did a bad job of reading the docs: 

> patternExtension
>
> Sets the panel name and language for the code tab on the styleguide. Since this only accepts one value, this is a place where mixed pattern trees (different PatternEngines in the same instance of Pattern Lab) does not quite work.

Does this also mean that PL is supposed to work with mixed engines? Or is this an accidental feature that will work with some engines but not with others?

**Comment by engelfrost** [comment]
PR: https://github.com/pattern-lab/website/pull/115
