### ISSUE TITLE
Items in the MQ list are broken after simply adding bootstrap3 to the project

### ISSUE THREAD

**Issue by getsetbro** [pattern-lab/patternlab-node#98]
Here is an example. Started with latest plnode-v8. Added bootstrap3 and then tried the items added to the MQ list. I am interested to know if bs3 does MQs in a way that plnode does not expect.
http://getsetbro.com/pl-nodeV8/public/

**Comment by bmuenzenmeyer** [comment]
This makes sense, and is sorta by-design, as the media query hunter is searching for ALL media queries in the CSS you ship. Bootstrap is loaded with media queries, hence the giant list.

 I need to look to see if there is a smart way to black-list library css.

**Comment by dmolsen** [comment]
@bmuenzenmeyer -

I think this is a bug. The [lines in question](https://github.com/pattern-lab/patternlab-node/blob/e61b6f0ec14b4706d19d3d482af122c39577080c/builder/media_hunter.js#L27-L33) make an assumption that a space is going to be in the returned match when it's actually optional. Hence the `(min-width:992px` in @getsetbro's returned results. It might be better to re-run the regex against the results of the first match and then explicitly pull the appropriate matching element. e.g.

```js
var matches = safeContents.match(/@media.*\((min|max)-width:([ ]+)?(([0-9]{1,5})(\.[0-9]{1,20}|)(px|em))/g);
for(var i = 0; i < matches.length; i++){
	var breakpointBits = matches[i].match(/@media.*\((min|max)-width:([ ]+)?(([0-9]{1,5})(\.[0-9]{1,20}|)(px|em))/);
	if(patternlab.mediaQueries.indexOf(breakpointBits[3]) === -1){
		patternlab.mediaQueries.push(breakpointBits[3]);
	}
}
```

I also added the `@media.*` to the regex because `min|max-width` exist for other elements. I got [bit by that](https://github.com/pattern-lab/patternlab-php-core/blob/1f971b21e16294a3457d2d51684c7b384a904ce2/src/PatternLab/Builder.php#L63) too.

PS - that's untested code. i did some testing with similar code but didn't run that exact code above hence no PR.

**Comment by bmuenzenmeyer** [comment]
@dmolsen thanks for weighing in - regex's aren't my forte so this isn't as strong as it should be. I understand what needs to be done and @getsetbro has a perfect test case which I will incorporate.

I'll try to get this into 0.8.1 (or at least in dev branch) by end of week
